### ISSUE TITLE
self.childVCs里的controllers动态创建问题

### ISSUE THREAD

**Issue by CH305426** [QuintGao/GKPageScrollView#10]
由于需求原因，我需要动态创建childVCs，发现滚动紊乱

发现 [self configListViewScroll];在init里处理，就很容易到中第一次进来，设置不成功，建议单独把方法拉出来处理

**Comment by QuintGao** [comment]
你好，可以参考demo中的懒加载列表的处理方式

**Comment by 986138497** [comment]
你好,UIViewController+GKCategory 分类会直接影响我们项目中的(某些界面不能侧滑),请问怎么修改

**Comment by QuintGao** [comment]
@986138497 你是用了GKNavigationBarViewController这个库吗？
