### ISSUE TITLE
2个问题：1.修改frame会错乱；2.不支持动态修改吸顶高度

### ISSUE THREAD

**Issue by cashgift** [QuintGao/GKPageScrollView#104]
问题1复现：
Demo中GKWBViewController.m，在- (void)more中重新设置frame，例如：
`[self.pageScrollView mas_remakeConstraints:^(MASConstraintMaker *make) {
        make.top.mas_equalTo(100);
        make.left.mas_equalTo(0);
        make.bottom.mas_equalTo(0);
        make.right.mas_equalTo(0);
}];`
会发现布局乱了

问题2：
当我需要动态修改吸顶高度时（ceilPointHeight）发现并不支持，看了下源码发现listContainerView的尺寸在一开始就固定了，其实这也是问题1带来的附加问题，我觉得应该支持我在后续某个时间点去修改ceilPointHeight的需求，很实际的场景：
当应用加载后发现需要展示吸顶公告，那么我当前的ceilPointHeight属性就一定要更改了

**Comment by QuintGao** [comment]
最新版已修复
