### ISSUE TITLE
您好如果基于 豆瓣的效果实现喜马拉雅详情页的效果 该如何修改 

### ISSUE THREAD

**Issue by qwerOC** [QuintGao/GKPageScrollView#105]
目前我实现了三段拖动 有个问题请教 拖动到中间位置时 如何处理列表的滚动呢

https://user-images.githubusercontent.com/17760059/164498272-40954be1-dc7c-455f-8735-67a900ef8c92.mov

**Comment by QuintGao** [comment]
可以把手势加到GKPageSmoothView上，然后根据代理去做相应的处理

**Comment by qwerOC** [comment]
没太理解 GKPageSmoothView 添加拖动手势后 内部的bottomContain 手势还需要么？

**Comment by QuintGao** [comment]
就是把内部那个手势添加到GKPageSmoothView上，但具体我也没试过，不知道行不行
