### ISSUE TITLE
主列表滑动时，子列表内容抖动

### ISSUE THREAD

**Issue by 347008893** [QuintGao/GKPageScrollView#108]
最新版本，当主列表滑动时，子列表出现抖动。当子列表为 tableView collectionView wkwebview时都遇到此问题

**Comment by QuintGao** [comment]
我demo能复现吗

**Comment by 347008893** [comment]
> 

demo也有此问题，当手势向上滑动并迅速离开触碰时，会出现子列表第一个cell向上偏移后恢复的抖动的感觉[](url)

**Comment by 347008893** [comment]
![Simulator Screen Recording - iPhone 12 Pro - 2022-06-22 at 14 08 19](https://user-images.githubusercontent.com/15334927/174955799-d6c0d99c-c0de-4c52-8be2-c8877f89c0f0.gif)

**Comment by 347008893** [comment]
![Simulator Screen Recording - iPhone 12 Pro - 2022-06-22 at 14 10 36](https://user-images.githubusercontent.com/15334927/174956022-740c94ed-cf40-47fd-adac-ae8ab7cd6459.gif)

**Comment by QuintGao** [comment]
试下最新demo，看还有没有抖动问题

**Comment by 347008893** [comment]
似乎好了很多，但仍有轻微抖动。十分感谢您的支持！

**Comment by QuintGao** [comment]
已发布1.7.3版本
