### ISSUE TITLE
GKSmoothView动态修改header高度

### ISSUE THREAD

**Issue by SanLiMikasa** [QuintGao/GKPageScrollView#109]
GKSmoothView动态修改header高度，调用refreshHeaderView方法后界面出现多种bug ，demo可复现

**Comment by QuintGao** [comment]
如何复现

**Comment by SanLiMikasa** [comment]
> 

![image](https://user-images.githubusercontent.com/11350516/178885930-fd920da7-a3db-46bf-a894-287c45ca3d1d.png)

**Comment by QuintGao** [comment]
已修复
