### ISSUE TITLE
滚动问题

### ISSUE THREAD

**Issue by BowenCoder** [QuintGao/GKPageScrollView#11]
你好，问一个问题。我想简写一个类似的两个scrollview滚动的功能，当mainscrollview滑动到底部，再滑动的时候，childscrollview就不滚动了，代理也不走了。你是怎么做到的啊，我看了你的代码没看到关键点。

**Comment by QuintGao** [comment]
滑动处理在：listScrollViewDidScroll  和  mainScrollViewDidScroll  这两个方法中，你认真看看就知道了

**Comment by BowenCoder** [comment]
我之前看了，没有找到我的关键点。我在你的这两个方法中直接return了。你的mainTableView滑动到底部，再往上面滑动，mainTableView和listContainerView都会滑动。我的只响应mainTableView 的scrollViewDidScroll, listContainerView不响应scrollViewDidScroll。初步怀疑手势问题，看了你的也只在GKPageTableView处理了一下
