### ISSUE TITLE
主列表滑动到吸顶临界点后isMainCanScroll属性就一直为NO

### ISSUE THREAD

**Issue by mzgreat521** [QuintGao/GKPageScrollView#111]
手指在headview或segmentview上滑动，达到临界点后isMainCanScroll就一直为NO，而手指在子列表上滑动，就不会这样。然后是否可以将一些属性声明到外面，例如isScrollToCritical、criticalOffset、criticalPoint等，主要是为了解决动态改变headview时的页面滑动问题，因为在吸顶状态下，动态改变headview高度的时候是会有继续保持吸顶状态的场景，而且不保持吸顶的话，滑动子列表就会有页面跳动。而且针对scrollToCriticalPoint这个方法最好能加个是否有动画的参数animated，有时候滑动到临界点是不需要动画的。

**Comment by mzgreat521** [comment]
额，没想到你这么快就更新发版了。“滑动到原点和临界点方法新增是否需要动画方法”这个如果增加不需要动画的方法，有个细节需要处理下，就是isScrollToCritical这个属性在不做动画的时候需要另外处理下，因为这时候是不会走scrollViewDidEndScrollingAnimation这个回调的，如果调用一次scrollToCriticalPoint后再调用的话，应该就会直接return了。

**Comment by mzgreat521** [comment]
我刚用最新版测试了下，如果子列表不满一屏的话，吸顶临界点状态的时候就不能向下滑动了，只有满一屏的子列表才能向下滑动。之前的版本还是可以滑动的，只是isMainCanScroll一直为NO，而现在最新版却是滑不动了。而且之前手指在segmentview上是可以在吸顶状态时向下滑动的，现在最新版却不能了，请你再看下啊。

**Comment by QuintGao** [comment]
```
如果子列表不满一屏的话，吸顶临界点状态的时候就不能向下滑动了，只有满一屏的子列表才能向下滑动
```
这个没发现有问题啊，我demo能复现吗？

```
之前手指在segmentview上是可以在吸顶状态时向下滑动的，现在最新版却不能了
```
这个不太好处理，而且我看b站也是这样，就不改了。

**Comment by mzgreat521** [comment]
> 
> 这个没发现有问题啊，我demo能复现吗？
> 
> 
> 这个不太好处理，而且我看b站也是这样，就不改了。

你的demo都是超过一屏的数据，复现不了，需要子列表数据不满一屏或是没有数据，你可以试下这样的场景，我这边是已经测试复现了的。之前1.7.5的版本是好的，更新后就滑不动了，而且1.7.5的版本手指在segmentview上是可以滑动的啊，只是isMainCanScroll属性没有变化，更新后就不能滑动了。

**Comment by QuintGao** [comment]
更新下demo，修改header高度里面有不足一屏的场景，没问题啊。另外1.7.5版本能滑动是有bug

**Comment by mzgreat521** [comment]
嗯，那先这样吧，暂时应该没什么问题了。

**Comment by mzgreat521** [comment]
![截屏2022-09-27 10 27 22](https://user-images.githubusercontent.com/16814904/192417551-b73c7ad1-c4b9-49fc-96c8-4bd85e589560.png)
这里是否可以增加一个属性来做区分判断？如果需要保持临界点状态，就滚动到临界点，如果不需要，就不用滚动，而是header变高后，就不再是临界点状态，并改变主列表的偏移量。

**Comment by mzgreat521** [comment]
> 

额，这些提到的修改是不好实现吗？

**Comment by QuintGao** [comment]
已优化
