### ISSUE TITLE
在某种情况下会触发滚动的死循环

### ISSUE THREAD

**Issue by houjiahui90** [QuintGao/GKPageScrollView#113]
![image](https://user-images.githubusercontent.com/12094766/190109991-f503feb9-ac05-4e70-b6c2-463b7077fbf0.png)
如图577行代码不够健全，在操作时offsetY的值能够变为-0.3 (测试-0.1~-0.5都会触发)，然后进行滚动时，触发了KVO操作但TableView并不会去实际滚动，导致再次刷新这个判断又成立，然后继续滚动，再触发KVO，最终死循环。
bug原因：视网膜屏幕绘制精度问题
测试设备iPad OS 15.7

**Comment by QuintGao** [comment]
模拟器能复现吗，我这测试没问题

**Comment by houjiahui90** [comment]
不是用的模拟器，是在真机上，测试设备是新款iPad Air，模拟器上肯定不会发生像素对齐的问题。

**Comment by YuanJiaShuai** [comment]
我目前会在iOS 11的设备上偶现 UI卡死的情况，不能滑动不能点击，不确定是不是这个原因导致 版本是1.8.0
