### ISSUE TITLE
启动crash

### ISSUE THREAD

**Issue by ITzhao** [QuintGao/GKPageScrollView#115]
dyld: Library not loaded: /usr/lib/swift/libswiftCoreGraphics.dylib
  Referenced from: /private/var/containers/Bundle/Application/D726642D-1384-4198-A320-36868387534E/xxx.app/Frameworks/GKPageScrollView.framework/GKPageScrollView
  Reason: image not found

xcode14;
iOS 12.0;
真机

**Comment by QuintGao** [comment]
怎么集成的？

**Comment by ITzhao** [comment]
pod导入，已解决，Xcode14升级导致iOS11,12的错误，可以兼容下。

**Comment by jinliyuelong** [comment]
怎么解决的

**Comment by ITzhao** [comment]
> 怎么解决的

工程中添加，以及报错的第三方中添加
Build Setting ->Other Link Flags下添加-Wl,-weak-lswiftCoreGraphics

**Comment by jinliyuelong** [comment]
这样设置也不行呀
