### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by lijiee** [QuintGao/GKPageScrollView#117]
源   // MARK: - Private Methods
    fileprivate func configListViewScroll() {
        if (self.delegate!.listView?(in: self).count) ?? 0 > 0 {
            for (_, value) in (self.delegate!.listView?(in: self).enumerated())! {
                value.listViewDidScroll {(scrollView) in
                    self.listScrollViewDidScroll(scrollView: scrollView)
                }
            }
        }
    }
  
 修改 // MARK: - Private Methods
    fileprivate func configListViewScroll() {
        if (self.delegate!.listView?(in: self).count) ?? 0 > 0 {
            for (_, value) in (self.delegate!.listView?(in: self).enumerated())! {
                value.listViewDidScroll {[weak self] (scrollView) in
                    self?.listScrollViewDidScroll(scrollView: scrollView)
                }
            }
        }
    }

**Comment by QuintGao** [comment]
最新版已修复
