### ISSUE TITLE
'UICollectionView (<UICollectionView 0x11883c800>) is stuck in its update/layout loop

### ISSUE THREAD

**Issue by DreamHeader** [QuintGao/GKPageScrollView#122]
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView (<UICollectionView 0x11883c800>) is stuck in its update/layout loop. This can happen for various reasons, including self-sizing views whose preferred attributes are not returning a consistent size. To debug this issue, check the Console app for logs in the "UICollectionViewRecursion" category. In particular, look for messages about layout invalidations, or changes to properties like contentOffset (bounds.origin), bounds.size, frame, etc.'
terminating with uncaught exception of type NSException

你好在IOS 15以上的手机 在demo 仿豆瓣电影页面的列表 如果把GKDBListView  中改为collection view 然后代理数据条数 改为0 比定闪退 麻烦看看

**Comment by DreamHeader** [comment]
![image](https://user-images.githubusercontent.com/35476529/211259364-217f179c-a289-4074-b217-ebeb7fbbef0f.png)

**Comment by QuintGao** [comment]
![image](https://user-images.githubusercontent.com/13514024/211270669-ca35711a-6928-4673-9a4c-1afd93f994bf.png)
布局类这样处理一下

**Comment by DreamHeader** [comment]
谢谢 解决了。能说下 你是如何定位到这个问题的点的么。我看了很久

**Comment by QuintGao** [comment]
这个问题很早之前就有，collectionView的contentSize过小的时候就会出现

**Comment by DreamHeader** [comment]
![image](https://user-images.githubusercontent.com/35476529/211454422-582ee2f0-cf7e-47ce-be7d-0a50e7209343.png)
这个方法这样的处理 会导致左右滑动 第一次出现的列表 会从滑动一半距离的视图直接闪到最下边。有没有什么办法能够解决
