### ISSUE TITLE
请教下使用了JXCategoryTitleView作为页面指示器，放在segmentedViewInPageScrollView中，在水平滑动时，会导致整体页面上下滑动

### ISSUE THREAD

**Issue by Livjxbill993** [QuintGao/GKPageScrollView#123]
如何监听JXCategoryTitleView的左右滑动

**Comment by QuintGao** [comment]
[手势处理](https://github.com/QuintGao/GKPageScrollView/blob/master/Document/手势处理.md)

**Comment by Livjxbill993** [comment]
像其它的UIScrollView都可以监听 就是JXCategoryTitleView这个导航条是UIView还是监听不了

![Simulator Screen Shot - iPhone 12 Pro - 2023-03-01 at 13 39 19](https://user-images.githubusercontent.com/47563697/222054669-345b137a-60d5-4708-a0f5-1978b32d94f4.png)

**Comment by Livjxbill993** [comment]
红色方块的UIScrollView代理下就可以监听   这个JXCategoryTitleView左右滑动即会导致页面上下滑动 ，试了好几次还是不知道该怎么监听

**Comment by QuintGao** [comment]
建议使用方法三
