### ISSUE TITLE
contentinset.top导致的问题

### ISSUE THREAD

**Issue by yxg0728** [QuintGao/GKPageScrollView#124]
![企业微信截图_86a31837-1f42-476d-85d0-40c55cd0f873](https://user-images.githubusercontent.com/21213065/225581802-1e2efa90-2d05-4a8b-8a7a-73b27b9ec8d3.png)

您好，我在使用GKPageSmoothView时，如果tableview设置了分区头，当向上滑动时，红色的分区头没有一起向上滑动，因为设置了tableview的contentinset.top的缘故，这个问题可以处理一下吗？

**Comment by QuintGao** [comment]
@yxg0728 这个目前处理不了，想正确显示的话只能用GKPageScrollView
