### ISSUE TITLE
Header中包含可滑动视图，如何处理手势冲突

### ISSUE THREAD

**Issue by Cheng455153666** [QuintGao/GKPageScrollView#125]
https://user-images.githubusercontent.com/11585827/230340922-463c6b82-ff84-4e96-a656-16d7de69323c.mp4

**Comment by Cheng455153666** [comment]
参考Header 的Demo中把回调给ScrollView加上后，滑动效果不佳

**Comment by QuintGao** [comment]
[手势处理](https://github.com/QuintGao/GKPageScrollView/blob/master/Document/%E6%89%8B%E5%8A%BF%E5%A4%84%E7%90%86.md)，看看这里的处理，推荐方法三

**Comment by Cheng455153666** [comment]
好的，感谢，确实可以解决，只不过感觉对访问权限的破坏挺大_(¦3」∠)_，好多藏的很深的子视图都不得不丢出来了
