### ISSUE TITLE
仿抖音崩溃

### ISSUE THREAD

**Issue by 173323222** [QuintGao/GKPageScrollView#129]
由于示例中创建categoryView时，_categoryView.listContainer = (id<JXCategoryViewListContainer>)self.pageScrollView.listContainerView这其中，示例代码listContainerView里面contentScrollView是有collection的，而新版中没有

**Comment by QuintGao** [comment]
啥意思，我demo会崩溃吗？最新版用的是1.8.8？

**Comment by 173323222** [comment]
按照你demo的方式集成PageScrollView，在创建'JXCategoryTitleView'时，给JXCategoryTitleView.listContainer赋值会崩溃，查看到demo里面创建时方法更改了，现在只有一个delegate，但是里面的collection都创建了。崩溃代码'_categoryView.listContainer = (id<JXCategoryViewListContainer>)self.pageScrollView.listContainerView;'

1.我昨天下载的demo，请问demo里面使用的PageScrollView的版本号是多少？
2.我按照教程在podfile里面引用，在podfile.lock里面看到GKPageScrollView和GKPageSmoothView均为1.8.6

**Comment by 173323222** [comment]
我将版本号指定为你说的1.8.8，崩溃消失

**Comment by QuintGao** [comment]
是的，最新版修改了懒加载的集成方式
<img width="859" alt="image" src="https://github.com/QuintGao/GKPageScrollView/assets/13514024/b182172b-58e7-4f9c-8edd-aa122cc4da59">
