### ISSUE TITLE
方法使用版本判断问题

### ISSUE THREAD

**Issue by EdenChow** [QuintGao/GKPageScrollView#13]
文件名 GKPageListContainerView.h
![图片](https://user-images.githubusercontent.com/13067657/56336317-7b3afa80-61d2-11e9-8953-b252b8d8b7ad.png)
contentInsetAdjustmentBehavior 这个属性，需要在iOS 11 系统才有，这个判断需要改一下。

**Comment by QuintGao** [comment]
多谢提醒，问题已修复。

**Comment by YuanJiaShuai** [comment]
这个问题好想没有更新呀，GKPageListContainerView 文件 46行，还是iOS 10.0 做判断的

**Comment by QuintGao** [comment]
改了啊，你下的是最新版吗
