### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by chensunwang** [QuintGao/GKPageScrollView#130]
禁止主页滑动的类文件：当isLazyLoadList = false时，GKPageScrollView文件中614行中pageView = (self.delegate.pageView?(in: self))!的强取值报错闪退。包括在demo中也是一样会出现。

**Comment by QuintGao** [comment]
<img width="1118" alt="image" src="https://github.com/QuintGao/GKPageScrollView/assets/13514024/13f4e0ae-1f49-4dd8-844d-ce939851bb52">
非懒加载方式需要实现这两个协议哈
