### ISSUE TITLE
2个问题，第一个是页面发生漂移，第二是内容不够一屏不能下拉

### ISSUE THREAD

**Issue by 173323222** [QuintGao/GKPageScrollView#131]
我们使用此控件中出现了问题，我们使用这个库仿写小红书的个人页面：
1.我们在这个页面滑动了之后，切换页面或者进入字页面，再次回到这个页面时，mainTableView的contentOffset.y自己发生了变化， 并且，currentListScrollView 在我这里是一个UIViewController，里面有一个collectionView，这个collectionView也发生了变化
    我的解决办法，只能解决mainTableView的问题，但是collectionView不能解决
    解决办法，在页面viewDidDisappear的时候记录下当前mainTableView 和 currentListScrollView 的contentOffset.y，再次进入页面在viewwillappear里面设置contentoffset，只有mainTableVIew 生效了，collectionVIew还是在顶点。
 

2.当currentListScroll里面的内容向上滑动时，不够当前屏幕大小时，不能向下滑动

**Comment by QuintGao** [comment]
能提供下demo 吗

**Comment by 173323222** [comment]
UI 的demo可以的，但是没有数据和网络请求。

**Comment by 173323222** [comment]
而且为发现，我在设置导航和tabbar的时候会导致这些问题，并且我的项目中使用了QMUI，里面到navibar runtime的时候会从新刷新这个页面



项目太老了，新接手的，问题较多

**Comment by QuintGao** [comment]
QQ：1094887059

**Comment by 173323222** [comment]
感谢大佬的解决方案
