### ISSUE TITLE
如果在子页面增加了tableview的索引情况下，索引的点击事件会失效

### ISSUE THREAD

**Issue by aiyouBug** [QuintGao/GKPageScrollView#132]
将源码中
-(NSArray<NSString *>*)sectionlndexTitlesForTableView:(UITableView *)tableView设置为nil之后还是无法通过点击索引实现
滑动tabled的效果，大佬有啥解决方案吗

**Comment by QuintGao** [comment]
最新版已支持，可查看demo中的子列表索引
