### ISSUE TITLE
使用中碰到的几个问题

### ISSUE THREAD

**Issue by Ting-coder** [QuintGao/GKPageScrollView#14]
你好，使用过程中遇到几个问题。
1、如果mainTableView滚动了一段距离，那么点击状态栏回滚顶部以后，上拉的时候头部距离会直接偏移。
2、直接拖拽头部会卡到JXSegment的头部位置，mainTableView不会继承头部滚动的加速度。
3、头部中添加CollectionView的横向滚动，和纵向滚动的手势可以共存，既可以横向滚动也可以纵向滚动，无法保证同一个时间只有一种手势。
4、mainTableView的滚动有时候手势无法响应的问题。
期待您能尽快解决这些存在的问题。

**Comment by QuintGao** [comment]
1、已修复
2、我这个不支持滚动头部列表带加速度
3、我写了个demo HeaderScroll可以查看
4、未发现此问题

**Comment by Ting-coder** [comment]
感谢您的回复
