### ISSUE TITLE
如何实现飞猪这种效果

### ISSUE THREAD

**Issue by huangfangkai** [QuintGao/GKPageScrollView#142]
![效果](https://github.com/QuintGao/GKPageScrollView/assets/13741702/5a5a8494-85a0-4ca9-abad-349b7a79a7a9)

**Comment by huangfangkai** [comment]
>

**Comment by huangfangkai** [comment]
![ezgif-1-062baba0a6](https://github.com/QuintGao/GKPageScrollView/assets/13741702/5fc1a085-808d-4660-89ef-dd26ca48cb0f)

**Comment by FunnyerFeng** [comment]
下拉刷新的库可以实现，和这个库没啥关系
