### ISSUE TITLE
豆瓣效果，Header 上划带动下面悬浮 tab滚动未到顶时，点击下面 tabs会发生页面抖动

### ISSUE THREAD

**Issue by JazzHunter** [QuintGao/GKPageScrollView#143]
QuintGao 您好，非常感谢您的框架。我在您的 Demo 里发现当 HeaderView 滚动至连带下面 tabs 滚动但是未到顶时，点击 Tab 名称进行切换，这时候页面会闪烁（OC 版本，Swift未发现），请问是一个 bug 么？
非常感谢！
![2024-07-04 08-44-09 2024-07-04 08_44_48](https://github.com/QuintGao/GKPageScrollView/assets/36096435/9d5f2af1-7427-48cd-96c3-f7c5f4b6df38)

**Comment by QuintGao** [comment]
最新版已修复

**Comment by Samuel-Xi** [comment]
感谢作者无私奉献，及时维护🤝🤝，正好遇到这个问题，折腾好久搞不定

**Comment by Samuel-Xi** [comment]
您好，我这里遇到这样一个问题，您看方便帮忙看看吗？底部的tableView被一个view挡住了，有时候又没有挡住，不知道是啥问题
![底部view挡住了segmentView下面的tableView](https://github.com/QuintGao/GKPageScrollView/assets/174760999/6f889dbb-0fd2-4c35-a26a-8c57c99a87b8)

**Comment by Samuel-Xi** [comment]
我隐藏了顶部的导航栏，自定义一个View做为导航栏使用，设置了_smoothView.ceilPointHeight = GK_STATUSBAR_NAVBAR_HEIGHT, smoothView从导航栏下方开始

**Comment by QuintGao** [comment]
可以弄个demo吗

**Comment by Samuel-Xi** [comment]
好的👌，感谢🤝，在项目里抽出来有点不太方便，我看看
