### ISSUE TITLE
触点在底部mainscrollView，滑动到吸附位置，下面的列表无法一起滚动？

### ISSUE THREAD

**Issue by zxfmpy** [QuintGao/GKPageScrollView#15]
触点在底部mainscrollView，滑动到吸附位置，下面的列表无法一起滚动？如demo中抖音，触点在上面头部，"作品"那个列表无法一起滚动?

**Comment by QuintGao** [comment]
是的，我这个不支持此功能

**Comment by QuintGao** [comment]
@Jacky-LinPeng 用GKPageSmoothView
