### ISSUE TITLE
能支持 VTMagic 吗？

### ISSUE THREAD

**Issue by Suzhibin** [QuintGao/GKPageScrollView#16]
能支持 VTMagic 吗？ https://github.com/tianzhuo112/VTMagic  感觉性能很好，我试了与GKPageScrollView 结合 但是上下滑动 主视图与子视图 各玩个的。

**Comment by QuintGao** [comment]
最新版增加了VTMagic使用的demo，可以看一下

**Comment by Suzhibin** [comment]
@QuintGao  给大佬提个建议  
- (BOOL)shouldLazyLoadListInPageScrollView:(GKPageScrollView *)pageScrollView{
    return NO;
}
这个代理 建议不要必须实现 ，老版本 升级 没添加这个方法都崩溃，可以设计一个默认为NO ，需要在实现yes的方法 或属性。 而且我感觉懒加载这种操作，不应该由这种框架级的架构去实施，应该叫给开发者结合业务自己来。

**Comment by QuintGao** [comment]
感谢建议，最新版已增加了可设置懒加载的属性。
