### ISSUE TITLE
子控制器如果是UIScrollView的时候，控制器不走scrollViewDidScroll方法

### ISSUE THREAD

**Issue by jolincheng** [QuintGao/GKPageScrollView#17]
子控制器如果是UIScrollView的时候，控制器不走scrollViewDidScroll方法

**Comment by QuintGao** [comment]
是不是没设置delegate

**Comment by jolincheng** [comment]
> 是不是没设置delegate

设置了代理，但是就是不走，然后我换成taleview设置代理uitableviewdelegate就可以

**Comment by QuintGao** [comment]
能提供使用的demo吗

**Comment by jolincheng** [comment]
> 能提供使用的demo吗

用了你的demo改了一下，用scrollview走了代理，但是我自己的我遵循了代理，也没有走scrollViewDidScroll，我在看看把
