### ISSUE TITLE
当其中一个page页回到顶部之后其他page的contentoffset 全部都回到了最顶部

### ISSUE THREAD

**Issue by FlyingNoob** [QuintGao/GKPageScrollView#18]
页面中有几个子tableview 当其中一个下啦回到最顶部之后，切换其他页的table 都回到了顶部最顶部。其实这个时候列表页是应该在之前滑动的位置

**Comment by QuintGao** [comment]
其中一个回到最顶部后headerView已经处于全部显示状态，如果其他列表页不回到最顶部滑动就会出现错乱
