### ISSUE TITLE
添加collectionview之后滑动很卡顿

### ISSUE THREAD

**Issue by pengxu1013** [QuintGao/GKPageScrollView#20]
在一个vc里同时添加了tableview和collectionview之后,滑动tableview正常,很顺畅,切换到collectionview之后上下滑动很卡顿,请问是什么原因?

**Comment by QuintGao** [comment]
有demo吗

**Comment by pengxu1013** [comment]
就直接按你添加tableview的方式复制一个collectionview出来 加进去 滑动就很卡顿，我已经暂时替换成tableview来显示了




            
            
                
                    
                            
                                
                            
                            
                                976996968
                            
                    
                        
                            
                                    邮箱：976996968@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2019年07月12日 11:03，QuintGao 写道： 有demo吗

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/QuintGao/GKPageScrollView/issues/20?email_source=notifications\u0026email_token=AEGSGZUKFOC6QR2FBYJLWO3P67YAPA5CNFSM4IB7VJXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZYRGQA#issuecomment-510726976",
"url": "https://github.com/QuintGao/GKPageScrollView/issues/20?email_source=notifications\u0026email_token=AEGSGZUKFOC6QR2FBYJLWO3P67YAPA5CNFSM4IB7VJXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZYRGQA#issuecomment-510726976",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by pengxu1013** [comment]
兄dei,就是把你抖音文件夹下的GKDYListViewController里的tableview换成了一个空数据的collectionview 然后就是我说的卡顿情况,你那边可以试一下的

**Comment by QuintGao** [comment]
我更新了demo，增加了collectionView使用，在测试里面，你可以看看

**Comment by pengxu1013** [comment]
你好,新加的demo我看了,怎么是继承于uiview的?不能直接继承于uiviewcontroller吗?可以的话给我个联系方式 我把demo发你看一下
