### ISSUE TITLE
列表点击无法跳转哦

### ISSUE THREAD

**Issue by jozdee** [QuintGao/GKPageScrollView#22]
发现self.navigationController 为nil无法push造成的，这个有什么好方法解决？只能传递controller过去？

**Comment by QuintGao** [comment]
你把列表控制器添加到当前控制器中就行了

**Comment by NSObject-RC** [comment]
> 发现self.navigationController 为nil无法push造成的，这个有什么好方法解决？只能传递controller过去？

请教一下，你这个是怎么处理的？

**Comment by QuintGao** [comment]
在创建子控制器的时候调用 [self addChildViewController:你的子控制器];，把子控制器添加到当前控制器。

**Comment by NSObject-RC** [comment]
> 在创建子控制器的时候调用 [self addChildViewController:你的子控制器];，把子控制器添加到当前控制器。

楼主看下刚刚提的一个issues，有具体的描述。
