### ISSUE TITLE
你好，在使用您的框架时调用[pageScrollView reloadData]时，会把系统的navigationBar给干掉吗

### ISSUE THREAD

**Issue by pcccccc** [QuintGao/GKPageScrollView#24]

**Comment by pcccccc** [comment]
版本：1.2.8

我在获取网络请求后，执行了reloadData方法，发现系统的导航栏被干掉了，如果注释掉该方法，就没有问题

**Comment by QuintGao** [comment]
GKPageScrollView没有对导航栏做任何处理，是不是你其他方法导致的，或者最好能提供复现的demo

**Comment by pcccccc** [comment]
目前暂时的解决方法是删除了GKNavigationBarViewController的引用。
后面有时间再测试一下是为什么产生了这个问题。
