### ISSUE TITLE
Xcode 11 iOS 13下闪退问题

### ISSUE THREAD

**Issue by huangyake** [QuintGao/GKPageScrollView#25]
GKPageScrollView.m

- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath {
    return self.frame.size.height - self.ceilPointHeight;
}

原因是, 在这里获取到的 self.frame.size.height 为0

**Comment by QuintGao** [comment]
具体怎么使用的呢，我测试demo中没有发现崩溃

**Comment by huangyake** [comment]
正常的使用方法, 从demo中拷贝的代码:  懒加载, viewDidLoad里加在viewController的view上, 然后使用Masonry

**Comment by QuintGao** [comment]
问题已修复
