### ISSUE TITLE
用了你滴框架 想做点击那个cell 进行置顶操作 

### ISSUE THREAD

**Issue by LAnqxpp** [QuintGao/GKPageScrollView#28]
[self.tableView selectRowAtIndexPath:indexPath animated:YES scrollPosition:UITableViewScrollPositionTop];  这句话没有有作用  大佬看下

**Comment by QuintGao** [comment]
需要先调用[self.pageScrollView scrollToCriticalPoint];  到达临界点后 再进行置顶操作

**Comment by LAnqxpp** [comment]
谢谢
