### ISSUE TITLE
1.使用懒加载崩溃问题2.列表控制器中的self.navigationController为nil，列表控制器没办法添加到当前控制器

### ISSUE THREAD

**Issue by NSObject-RC** [QuintGao/GKPageScrollView#30]
1.使用懒加载崩溃问题：
使用了JXCategoryView，JXCategoryListContainerView是高度封装的，它自动把列表控制器添加到JXCategoryListContainerViewController上。列表控制器与当前控制器中间隔了一个JXCategoryListContainerViewController，而JXCategoryListContainerViewController没办法实现GKPageListViewDelegate这个代理。造成了
"- (id<GKPageListViewDelegate>)pageScrollView:(GKPageScrollView *)pageScrollView initListAtIndex:(NSInteger)index" 这个方法无法返回有效代理。
崩溃输出：reason: 'child view controller:<列表控制器: 0x7fc60dd844e0> should have parent view controller:<当前控制器: 0x7fc60dd2cb30> but actual parent is:<JXCategoryListContainerViewController: 0x7fc60dc678e0>'

2.列表控制器点击self.navigationController为nil
因为1的问题导致列表控制器中的self.navigationController为nil，且没办法通过添加到当前控制器来解决。

可以不使用懒加载，且将当前控制器作为属性传递给列表控制器就没有以上问题，但是有点僵硬！

**Comment by QuintGao** [comment]
JXCategoryListContainerView不能和GKPageScrollView结合使用的
