### ISSUE TITLE
listScrollView 是 UICollectionView 的时候，如果数据源是0，没有调用scrollViewDidScroll这个代理方法。

### ISSUE THREAD

**Issue by zyvv** [QuintGao/GKPageScrollView#34]
listScrollView 是 UICollectionView 的时候，如果数据源是0，没有走 scrollViewDidScroll 这个代理方法，导致滑动卡顿。
但是同样是数据源没有数据，listScrollView 改成 UITableView，就一切正常。

**Comment by zyvv** [comment]
listScrollView 只能是 UITableView 类型吗？

**Comment by QuintGao** [comment]
UICollectionView需要设置alwaysBounceVertical = YES

**Comment by zyvv** [comment]
> UICollectionView需要设置alwaysBounceVertical = YES

soga, 谢谢！
