### ISSUE TITLE
嵌套互动处理

### ISSUE THREAD

**Issue by YuanJiaShuai** [QuintGao/GKPageScrollView#38]
```
// 处理左右滑动与上下滑动的冲突
- (void)horizonScrollViewWillBeginScroll;
- (void)horizonScrollViewDidEndedScroll;
```
代码里面提供的处理左右互动和上下滑动冲突的方法，感觉有些生硬，作者有没有更优雅的处理方式？

**Comment by QuintGao** [comment]
![image](https://user-images.githubusercontent.com/13514024/79419406-5649b500-7fe9-11ea-8671-f6821e47e50c.png)
可以通过上面的方法实现，设置GKPageScrollView mainTableView的gestureDelegate，并实现上面的方法

**Comment by YuanJiaShuai** [comment]
代码加上去了，但是不生效。我现在的情况是，header里面有多个collectionView，现在滑动head里面的collectionView，会触发pageScrollView上下滚动，我看demo里面有个例子，Head左右滑动的Demo，我把你上面的代码加进去，他也是不生效！

**Comment by QuintGao** [comment]
我更新了HeaderScroll的demo，你在照着试试呢

**Comment by YuanJiaShuai** [comment]
感谢作者给出的解决方案，非常棒，完美解决了我的问题！
