### ISSUE TITLE
导航栏状态切换

### ISSUE THREAD

**Issue by SmallMX** [QuintGao/GKPageScrollView#4]
目前导航栏状态切换需要在- (void)mainTableViewDidScroll:(UIScrollView *)scrollView isMainCanScroll:(BOOL)isMainCanScroll里面自己实现，希望能封装几种常见模式。

**Comment by QuintGao** [comment]
这个每个APP需要的情况都不一样，具体有哪些模式呢？

**Comment by SmallMX** [comment]
Dome里面不是已经有了吗

**Comment by QuintGao** [comment]
GKPageScrollView跟导航栏是没有关联的，所以还是自行处理的比较好。
