### ISSUE TITLE
GKPageListContainerCollectionView的Cell容器frame的y=22pt，并且底部还留白了22pt

### ISSUE THREAD

**Issue by Homin818** [QuintGao/GKPageScrollView#42]
v1.3.5
GKPageListContainerCollectionView里面的Cell的frame中的y不等于0，而是等于22，导致内容整体下移22pt，并且底部还保留了22pt，相当于整体内容减少了44pt

PS：GKPageListContainerCollectionView背景色是默认的黑色

**Comment by QuintGao** [comment]
没发现这个问题，你是怎么使用的？
