### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by CJHCAi** [QuintGao/GKPageScrollView#43]
// 设置导航item偏移量
    if (GKDeviceVersion >= 11.0 && !GKConfigure.gk_disableFixSpace) {
        self.layoutMargins = UIEdgeInsetsZero;
        
        for (UIView *subview in self.subviews) {
            if ([NSStringFromClass(subview.class) containsString:@"ContentView"]) {
                // 修复iOS11 之后的偏移
                subview.layoutMargins = UIEdgeInsetsMake(0, self.gk_navItemLeftSpace, 0, self.gk_navItemRightSpace);
                break;
            }
        }
    }

这种做法在 iOS 13 中会导致崩溃，崩溃信息如下：

Client error attempting to change layout margins of a private view
　　

试图更改私有视图的布局边距时出现错误

**Comment by QuintGao** [comment]
pod update 更新一下第三方库
