### ISSUE TITLE
子ViewController有一个固定在底部的view

### ISSUE THREAD

**Issue by maguoxi** [QuintGao/GKPageScrollView#44]
您好：
条件：子ViewController有一个固定在底部的view，父ViewController使用GKPageScrollView并添加子ViewController
问题：子ViewController底部的view一开始并不会显示，需要向上滑动一段距离才会显示。这段距离就是GKPageScrollView的headerView的高度。

我想让子ViewController固定在底部的view固定住，除了把view转移到父ViewController上，还有什么方法吗？

**Comment by QuintGao** [comment]
放在子VC中不能固定吗

**Comment by maguoxi** [comment]
您好
https://www.jianshu.com/p/120a55c648b7，这里有gif图可以看一下效果

**Comment by QuintGao** [comment]
打不开啊

**Comment by maguoxi** [comment]
这次可以了，原先图太大了

**Comment by QuintGao** [comment]
看到了，在listVC上处理就行吧，先放到listScrollView上，上滑出来固定后放到listVC的view上，下滑到可以隐藏的时候再放回listScrollView
