### ISSUE TITLE
collectionView无法滚动

### ISSUE THREAD

**Issue by wbxysf** [QuintGao/GKPageScrollView#45]
结构是：一级头部+pageScrollView+2个子控制器，其中一个一级控制器加二级头部高度为0+pageScrollView+子控制器。1.滚动到临界点，2.滚动其他子控制器列表，3.切到是collectionView的子控制器时无法滚动

**Comment by QuintGao** [comment]
#34

**Comment by wbxysf** [comment]
> #34

谢谢
