### ISSUE TITLE
其中一个分页的tableView的cell使用帧动画有问题

### ISSUE THREAD

**Issue by RCLOVETMH** [QuintGao/GKPageScrollView#47]
1、其中一个分页的tableView的cell使用帧动画有问题，
帧动画开始的时候，上下滑动的时候，帧动画会停止。不是cell复用的问题。
以上问题在使用最新的GKPageSmoothView的时候是ok的

2、但是[GKPageSmoothVie refreshHeaderView]，默认会滑到顶部

3、GKPageSmoothVie没有提供“DidEndDragging”、“DidEndDecelerating”、“WillBeginDragging”等滚动相关方法

**Comment by QuintGao** [comment]
1、能否提供demo，我测试没问题
2、试试最新版
3、这些方法需要自行处理

**Comment by isingle** [comment]
拖拽 tab下滑了， 会出现列表不下滑，再次上拉 tab 会出现新的列表  
![image](https://user-images.githubusercontent.com/2800988/103500596-7de9f180-4e86-11eb-881a-012ea7d3cdcf.png)

**Comment by QuintGao** [comment]
> 拖拽 tab下滑了， 会出现列表不下滑，再次上拉 tab 会出现新的列表
> ![image](https://user-images.githubusercontent.com/2800988/103500596-7de9f180-4e86-11eb-881a-012ea7d3cdcf.png)

@isingle 怎么操作出现的

**Comment by isingle** [comment]
列表往上滚动的时候， 下拉 tab

**Comment by QuintGao** [comment]
@isingle 最新版已修复

**Comment by QuintGao** [comment]
确定是最新版吗，下拉tab的时候列表停止滚动了没？

**Comment by isingle** [comment]
列表在滚动的过程中，下拉还是会出现

**Comment by QuintGao** [comment]
@isingle 
1、请先确认是否是最新版
2、列表滚动时下拉tab，列表滚动停止了没有
我这边测试是没有问题的，如果还有问题，请描述下具体操作步骤，谢谢

**Comment by isingle** [comment]
1，版本是 1.5.1


https://user-images.githubusercontent.com/2800988/103761520-c43f7c00-5051-11eb-88e7-e1995fb3075b.mov

**Comment by isingle** [comment]
> @isingle
> 1、请先确认是否是最新版
> 2、列表滚动时下拉tab，列表滚动停止了没有
> 我这边测试是没有问题的，如果还有问题，请描述下具体操作步骤，谢谢

1.5.1 应该是最新的吧，上面的视频操作会出现bug

**Comment by QuintGao** [comment]
找到原因了，iOS13以下的系统UIScrollView的isDragging属性不准确导致的，我咋说我这一直没问题😂

**Comment by isingle** [comment]
> 找到原因了，iOS13以下的系统UIScrollView的isDragging属性不准确导致的，我咋说我这一直没问题😂

嗯 那就是系统适配问题，可以用 isTracking 判断吗

**Comment by QuintGao** [comment]
> > 找到原因了，iOS13以下的系统UIScrollView的isDragging属性不准确导致的，我咋说我这一直没问题😂
> 
> 嗯 那就是系统适配问题，可以用 isTracking 判断吗

1.5.2版本已修复

**Comment by isingle** [comment]
> > > 找到原因了，iOS13以下的系统UIScrollView的isDragging属性不准确导致的，我咋说我这一直没问题😂
> > 
> > 
> > 嗯 那就是系统适配问题，可以用 isTracking 判断吗
> 
> 1.5.2版本已修复

为你点赞！！！
