### ISSUE TITLE
列表下拉刷新

### ISSUE THREAD

**Issue by jaye-github** [QuintGao/GKPageScrollView#49]
使用列表下拉刷新时，如果cell的数量比较多，当滑到下面，然后下拉滑上去，当滑的速度很快，会瞬间回到顶部了，不知是不是就是这样设计的呢？

**Comment by QuintGao** [comment]
没发现这个问题，我的demo有这个问题吗

**Comment by jaye-github** [comment]
> 没发现这个问题，我的demo有这个问题吗

demo也会这样

**Comment by QuintGao** [comment]
我试了demo没复现，需要怎么改动可以复现呢

**Comment by jaye-github** [comment]
> 我试了demo没复现，需要怎么改动可以复现呢

GKBaseListViewController 里的 numberOfRowsInSection,返回100个，列表刷新，然后滑到最后的数据，然后再滑上去，不过要用往下甩的动作，速度快点

**Comment by QuintGao** [comment]
还是没复现，到什么地方会瞬间回到顶部？

**Comment by jaye-github** [comment]
> 还是没复现，到什么地方会瞬间回到顶部？

基本手离开屏幕就马上回到顶部了

**Comment by QuintGao** [comment]
能否录个视频，我QQ1094887059

**Comment by jaye-github** [comment]
> 1094887059

录屏我发邮箱了

**Comment by QuintGao** [comment]
试了半天还是没复现/::-|

**Comment by jaye-github** [comment]
> 试了半天还是没复现/::-|

慢慢滑就不出现，是要很快的甩上去

**Comment by QuintGao** [comment]
我试出来了，快速滑动mainTableView的contentOffset.y 会突然变成负值。我加了个判断 你再试下看还有没有问题

**Comment by jaye-github** [comment]
> 我试出来了，快速滑动mainTableView的contentOffset.y 会突然变成负值。我加了个判断 你再试下看还有没有问题

好了，已经没有出现了，谢谢大佬
