### ISSUE TITLE
切换 Page 后如何将对应的 PageListView 置顶？

### ISSUE THREAD

**Issue by ansonham** [QuintGao/GKPageScrollView#51]
在使用 GKPageScrollView 的非懒加载模式时， 有这样一个场景，：

1. SegmentView  吸顶后将 Segment A 的对应的 PageListA 向上滑动一部分；
2. 切换到 Segment B, 然后下滑 PageListB，将 SegmentView 从吸顶状态变为非吸顶状态；
3. 切换到 Segment A,  实际操作中发现，当在此滑动 mainTableView 时，PageList A 会重置到置顶状态（这个逻辑不是很明白）。

做过的尝试：
在 SegmentView  的置顶跟非置顶状态切换瞬间，记录当前 mainTabView 的 lastOffset, 然后切换后，重新设置 mainTableView 的 offset 为当前记录的 lastOffset.

请问如何才能做到，**切换到 Segment A 后， PageListA 列表的第一个元素处于最顶部的置顶状态**，跟淘宝首页类似。

**Comment by QuintGao** [comment]
没发现有这个问题啊  我demo中有问题吗？

**Comment by ansonham** [comment]
> 没发现有这个问题啊 我demo中有问题吗？

demo 没问题，难道是因为我是用自定义 segmentView 的缘故？

**Comment by QuintGao** [comment]
有可能
