### ISSUE TITLE
非常奇怪的一个Bug..

### ISSUE THREAD

**Issue by damu-mu** [QuintGao/GKPageScrollView#54]
在我自己写项目的时候发生的这个问题.然后我又在`Demo`中复现了.
 在 `GKWYViewController` 这个控制器中. 将 `pageScrollView` 这个变量名 替换成为 `contentScrollView` 这个名字. 就会崩溃. 
报错信息: `[GKPageScrollView refreshControl]: unrecognized selector sent to instance 0x7fb14df0dcf0]`. 但是我搜索了 全局
也没找到 `refreshControl` 这个方法.

**Comment by QuintGao** [comment]
刚刚做了一个实验，在带有导航栏的控制器中，如果把非UIScrollView的类的属性命名为contentScrollView就会报这个错，我猜测这个contentScrollView应该是系统内部使用的属性，为了给UIScrollView滑动做处理用的。所以如果是非UIScrollView的类，属性命名的时候不要用contentScrollView。
