### ISSUE TITLE
吐槽一句

### ISSUE THREAD

**Issue by 295060456** [QuintGao/GKPageScrollView#56]
GK就老老实实做好导航，我看了下就GKPageScrollview来看应该没有https://github.com/pujiaxin33/JXPagingView做得好
我喜欢懒加载，GK+JX混用，demo我看了  集成的话有些小问题，demo写的不够清楚，我还是用JX算了，毕竟开发时间长而且团队开发，关注度较高。GK是个人开发吧。

@interface GKPageScrollView : UIView

/// 主列表
@property (nonatomic, strong, readonly) GKPageTableView   *mainTableView;

我为什么一定要是tableview呢？空白VC不行吗？给用户自定义VC...

核心在拉的时候图片变大，退回缩小，这部分应该有强烈注释。
-(UIView *)pageView{
    if (!_pageView) {
        _pageView = UIView.new;
        _pageView.backgroundColor = KGreenColor;
        
        [_pageView addSubview:self.categoryTitleView];
        [_pageView addSubview:self.scrollView];
        
    }return _pageView;
}

这个pageview的frame怎么定义的？我一头雾水，有点隐晦，最近状态不好没状态深入研究，只能开喷了...哈哈哈😃。直接就进协议了。
这就是集成成本。

**Comment by 295060456** [comment]
直接把scollview 封装到内层，外界让用户进VC。傻瓜式操作多好。

**Comment by 295060456** [comment]
建议学习下jx的@interface PagingViewController : UIViewController这个类，你可以看到他是继承UIViewController而不是其他乱七八糟的。
这个类的实现也只有100来行，没有多的协议，我主要担心多了以后代码内部冗余过多，而且增加冲突的风险。还有啊我看你虽然实现了功能 但是你定义scollview和paseView在外层干嘛？代码冗余，我看不懂里面的层级结构，而且scollview里面我最烦的就是那些数据计算。你放在外层，用户有那个闲心和能力基本也自己写了不会用你这个。

**Comment by QuintGao** [comment]
1、JXPagingView比我这个写得好没错，但是只支持JXCategoryView，对于喜欢用WMPageController，VTMagic的就没法用
2、我这个支持懒加载和非懒加载的方式，多看看demo就能看懂，可以根据自己的喜好选择
3、至于你说的PagingViewController那只是人家demo里面的基类，你可以用UIViewController，也可以用UIView
4、最后，你觉得JXPagingView好去用就是了，没人逼着你用我这个。

**Comment by 295060456** [comment]
你一点都不谦虚
