### ISSUE TITLE
延续滑动有问题，切换到其他滑动列表点击顶部返回到顶部。在切换到另一个列表，无法滑动顶部，只能滑动子列表

### ISSUE THREAD

**Issue by UncleJoker** [QuintGao/GKPageScrollView#57]

**Comment by caicai0525** [comment]
滑动列表是UITableView类型的时候会有这个bug，请问您解决了吗

**Comment by QuintGao** [comment]
我demo能复现这个问题吗，或者提供下demo，方便测试

**Comment by caicai0525** [comment]
> 我demo能复现这个问题吗，或者提供下demo，方便测试

demo可以复现，等UITableView加载完，切换到UICollectionView，再切回到UITableView，头部视图无法滑动

**Comment by QuintGao** [comment]
确实 点击切换的时候有问题，我抽空看下

**Comment by QuintGao** [comment]
最新版已修复
