### ISSUE TITLE
当子视图中有两个 tableview 的时候，切换滑动会有问题

### ISSUE THREAD

**Issue by zrx89757** [QuintGao/GKPageScrollView#58]
前置条件：某个页面使用了 GKPageScrollView，它用懒加载方式加载两个子视图A，B；其中 B 内部有左右排列的两个 tableview c，d；c 列表展示分类，d 列表展示某个分类下的店铺；所以 c 列表的切换会导致 d 列表的刷新。
问题描述：当选中某个分类后，滑动右侧的 d 列表到一定 offset，然后往下滚动 c 列表，停住，再将 c 列表滚回到 offset.y = 0，然后继续下拉，使最外层的 GKPageScrollView 触发下拉 bounce，会发现，d 列表也自动回到了 offset.y = 0 的位置。

**Comment by QuintGao** [comment]
离开临界点后所有的列表scrollView都会恢复到初始位置

**Comment by zrx89757** [comment]
emmm
