### ISSUE TITLE
你好，这个库是否考虑加入缓存？

### ISSUE THREAD

**Issue by FaDeve** [QuintGao/GKPageScrollView#6]
看了你的 demo，发现有集成 WMPage,但是就用不了 JXCategory，所以有没有考虑加入控制器的缓存，类似 WM 那张操作，但是又能结合 JXCategory的使用？

**Comment by QuintGao** [comment]
1、"发现有集成 WMPage,但是就用不了 JXCategory"，这个什么意思，这两个没有是互不影响的啊。
2、
GKPageScrollView并没有对控制器有任何操作，所以缓存并不是我这边能考虑的

**Comment by FaDeve** [comment]
可能之前描述不太清晰,是这样的.以网易云音乐demo 为例,一push进来,所有的列表控制器就全部加载完了,那如果对应的子列表数量多,且列表内容复杂,那对内存是很消耗的,所以我想的是是否考虑加入缓存机制,比如进来只加载选中的控制器,滑动的时候再加载相应的列表内容

**Comment by QuintGao** [comment]
demo中我只是为了方便，把控制器全部加载完成，实际操作中并不会这样写，另外对于缓存的操作JXCategoryView中有JXCategoryListCollectionContainerView这个类，具体使用可下载demo查看

**Comment by FaDeve** [comment]
了解，不知道你实际操作中，是怎么处理的这控制器缓存的

**Comment by QuintGao** [comment]
上面不是说了吗，可以使用JXCategoryView的JXCategoryListCollectionContainerView这个类实现缓存

**Comment by QuintGao** [comment]
你好，最新版已增加基于collectionView实现的缓存功能
