### ISSUE TITLE
GKSmoothListView数据少headview都把collectionview内容给盖住了

### ISSUE THREAD

**Issue by FullStackEngineer-Zpf** [QuintGao/GKPageScrollView#60]
#GKSmoothListView数据少headview都把collectionview内容给盖住了

**Comment by QuintGao** [comment]
什么意思？我测试没啥问题啊

**Comment by FullStackEngineer-Zpf** [comment]
OC:GKSmoothListView 类 把属性 count改成 =1 或者3. 然后往上滑动, 上方的导航+分类盖住了collectionView item 的显示. 还不明白 加我qq:850944623
