### ISSUE TITLE
GKViewControllerPopDelegate 协议并不存在 使用cocoapods导入OC1.50版本

### ISSUE THREAD

**Issue by zakpsycho** [QuintGao/GKPageScrollView#61]
今天使用cocoaPods导入OC的1.50版本后 照着demo使用时 发现GKViewControllerPopDelegate 协议不存在库里，想询问一下什么情况？ 已导入<GKPageScrollView/GKPageScrollView.h> <GKPageSmoothView/GKPageSmoothView.h>

**Comment by QuintGao** [comment]
这是另一个库的，GKNavigationBar

**Comment by zakpsycho** [comment]
收到，老哥能否加个联系方式询问一些关于库的问题，iOS新手

**Comment by QuintGao** [comment]
1094887059

**Comment by zakpsycho** [comment]
加了老哥～
