### ISSUE TITLE
iOS 12.1系统，跳转页面后header会自动偏移

### ISSUE THREAD

**Issue by Choice-Fei** [QuintGao/GKPageScrollView#64]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/13918369/105023399-df64af80-5a85-11eb-8401-92b510d35e7c.png">
跳转之前header已经悬停，跳转之后返回就这样了，ceilPointHeight吸顶高度设置为0，目前只在这个系统上发现

**Comment by QuintGao** [comment]
用的是GKPageScrollView还是GKPageSmoothView，具体怎么使用的？

**Comment by Choice-Fei** [comment]
用的GKPageScrollView，用法如下
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/13918369/105116773-5772ba00-5b06-11eb-829a-681c07fbbb14.png">

**Comment by Choice-Fei** [comment]
<img width="673" alt="image" src="https://user-images.githubusercontent.com/13918369/105123698-7f1c4f00-5b13-11eb-89cb-da6e5285f894.png">
很奇怪，我断点跟踪，发现12.1返回后这个方法走了。。。所以才会这样

**Comment by QuintGao** [comment]
我这试了没问题啊，你能在我抖音demo里面复现吗

**Comment by Choice-Fei** [comment]
> 我这试了没问题啊，你能在我抖音demo里面复现吗

嗯， 我自己重开了个demo试也没问题，我在排查是不是其他问题，用的wmpagecontroller然后其中一个子控制器是这个带悬停的页面

**Comment by Choice-Fei** [comment]
> 我这试了没问题啊，你能在我抖音demo里面复现吗

当返回的时候触发了viewDidLayoutSubviews这个方法，一级页面的高度先多了一个状态条的高度然后再变到正常高度,
然后触发了GKPageScrollView的layoutSubviews方法，就引起了偏移，不好意思，应该是我这边的页面结构引起的问题，我再排查排查
