### ISSUE TITLE
豆瓣效果底部列表问题

### ISSUE THREAD

**Issue by KerwinCheung** [QuintGao/GKPageScrollView#65]
豆瓣效果底部列表问题,在主视图没滑动的情况下拖拽底部列表上去>>滚动任意距离>>切换tab>>把列表拽下去>>主视图会发生偏移,列表会置顶,100%复现.
查看了代码和滚动代理等暂时没找到原因.先提出来.

**Comment by QuintGao** [comment]
你下载的是最新版的吗，这个问题应该修复过了

**Comment by KerwinCheung** [comment]
是的 最新版 我运行的是swiftdemo

**Comment by QuintGao** [comment]
最新版已修复
