### ISSUE TITLE
GKPageSmoothView-oc 主页无法下拉刷新

### ISSUE THREAD

**Issue by wangchunjiang** [QuintGao/GKPageScrollView#69]

**Comment by QuintGao** [comment]
最新版增加了下拉刷新的demo

**Comment by wangchunjiang** [comment]
你好,请问下- (id<GKPageSmoothListViewDelegate&gt;)smoothView:(GKPageSmoothView *)smoothView initListAtIndex:(NSInteger)index 我这里返回的是vc ,vc 内部放的collection ,这种情况下,如果主页如何刷新



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月16日(星期五) 下午2:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [QuintGao/GKPageScrollView] GKPageSmoothView-oc 主页无法下拉刷新 (#69)





 
最新版增加了下拉刷新的demo

**Comment by QuintGao** [comment]
方法一样，不过需要设置下MJRefreshHeader的ignoredScrollViewContentInsetTop这个属性为header容器的高度

**Comment by wangchunjiang** [comment]
请问下,pod 上的GKPageSmoothView 版本只到1.5.3吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月16日(星期五) 下午3:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [QuintGao/GKPageScrollView] GKPageSmoothView-oc 主页无法下拉刷新 (#69)





 
方法一样，不过需要设置下MJRefreshHeader的ignoredScrollViewContentInsetTop这个属性为header容器的高度

**Comment by QuintGao** [comment]
最新版是1.5.5，你用pod update更新下

**Comment by wangchunjiang** [comment]
谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月16日(星期五) 下午3:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [QuintGao/GKPageScrollView] GKPageSmoothView-oc 主页无法下拉刷新 (#69)





 
最新版是1.5.5，你用pod update更新下

**Comment by wangchunjiang** [comment]
你好,我在demo上- (id<GKPageSmoothListViewDelegate&gt;)smoothView:(GKPageSmoothView *)smoothView initListAtIndex:(NSInteger)index 返回vc ,刚进入页面的时候,headview 无法滑动刷新,有效区域只有底部的tab,切换菜单之后,head 就能响应下拉



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月16日(星期五) 下午3:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [QuintGao/GKPageScrollView] GKPageSmoothView-oc 主页无法下拉刷新 (#69)





 
最新版是1.5.5，你用pod update更新下

**Comment by QuintGao** [comment]
试了下并没有发现你说的情况，可否提供demo？

**Comment by wangchunjiang** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QuintGao/GKPageScrollView"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月19日(星期一) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [QuintGao/GKPageScrollView] GKPageSmoothView-oc 主页无法下拉刷新 (#69)





 
试了下并没有发现你说的情况，可否提供demo？

**Comment by wangchunjiang** [comment]
我实在您提供的demo,滑动延续示例上修改的,进入页面的第一个菜单 headview 无法响应刷新



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月19日(星期一) 上午10:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [QuintGao/GKPageScrollView] GKPageSmoothView-oc 主页无法下拉刷新 (#69)





 
试了下并没有发现你说的情况，可否提供demo？

**Comment by QuintGao** [comment]
加我QQ吧，方便些，1094887059
