### ISSUE TITLE
子控制器能加入懒加载吗？

### ISSUE THREAD

**Issue by EdenChow** [QuintGao/GKPageScrollView#7]
一共有 三个tab，`动态,文章,更多`
列如 第一次加载，单纯加载 动态这个控制器，但滑动到文件控制器，才加载它。

**Comment by QuintGao** [comment]
你好，最新版已支持懒加载功能。

**Comment by EdenChow** [comment]
> 你好，最新版已支持懒加载功能。

ths，我更新一下。
