### ISSUE TITLE
有关状态栏的问题！！！

### ISSUE THREAD

**Issue by kite424** [QuintGao/GKPageScrollView#70]
![2222](https://user-images.githubusercontent.com/57931594/115149372-57973d00-a096-11eb-95ea-b08de240f13b.jpg)
![111](https://user-images.githubusercontent.com/57931594/115149380-641b9580-a096-11eb-8314-efa17a464e97.jpg)
进入页面时，我想修改状态栏不被默认覆盖掉，并设置在navigationBar+状态栏高度下面进行Scroll，这个应该是否可以设置呢？

**Comment by QuintGao** [comment]
修改GKPageScrollView的y值在导航栏下面

**Comment by kite424** [comment]
> 修改GKPageScrollView的y值在导航栏下面

谢谢你的回答，我现在已解决。
