### ISSUE TITLE
tableView cell左滑删除与列表上下滑动冲突问题

### ISSUE THREAD

**Issue by stevema** [QuintGao/GKPageScrollView#71]
当我使用tableview cell的左滑删除时，如果我左滑的手势有一点角度的话，列表在cell左滑的同时会上下滑动，请问这个怎么做可以避免？

**Comment by QuintGao** [comment]
1、设置GKPageTableViewGestureDelegate
`_pageScrollView.mainTableView.gestureDelegate = self;`
2、实现代理方法，判断是否允许多手势
`#pragma mark - GKPageTableViewGestureDelegate
- (BOOL)pageTableView:(GKPageTableView *)tableView gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    if ([otherGestureRecognizer isKindOfClass:NSClassFromString(@"_UISwipeActionPanGestureRecognizer")]) {
        return NO;
    }
    return [gestureRecognizer.view isKindOfClass:[UIScrollView class]] && [otherGestureRecognizer.view isKindOfClass:[UIScrollView class]];
}`

**Comment by stevema** [comment]
> _UISwipeActionPanGestureRecognizer

谢谢！解决了
