### ISSUE TITLE
如何正确监听吸顶不吸顶状态？

### ISSUE THREAD

**Issue by Moussy** [QuintGao/GKPageScrollView#72]
请教下作者，我想在主控制器里监听吸顶不吸顶状态，有什么好的方法吗？用了以下的方法，不太管用
`- (void)mainTableViewDidScroll:(UIScrollView *)scrollView isMainCanScroll:(BOOL)isMainCanScroll {

    CGFloat scrollOffsetY = scrollView.contentOffset.y;
    if (scrollOffsetY >= self.headerView.height) {
        NSLog(@"$$$ -- 吸顶？");
    } else {
        NSLog(@"$$$ -- 不吸顶？");
    }
}`

**Comment by QuintGao** [comment]
isMainCanScroll为YES表示不吸顶，为NO表示吸顶

**Comment by Moussy** [comment]
非常棒👍 ，谢谢作者，太及时了
