### ISSUE TITLE
iOS12.1系统引起的bug，当在UITabController首页面使用时会发生

### ISSUE THREAD

**Issue by Choice-Fei** [QuintGao/GKPageScrollView#75]
复现场景：向上滑动一段距离后，然后push到子页面，然后pop回来，会触发系统的viewDidLayoutSubviews方法,进而触发控件的scrollDidScroll方法，所有列表偏移量都会被修正到CGPointZero(仅在iOS12系统上触发)

**Comment by QuintGao** [comment]
有复现的demo吗，我测试没发现问题
