### ISSUE TITLE
GKPageSmoothView 豆瓣电影主页Demo 会黑屏。视图在两个Cell间错乱了。

### ISSUE THREAD

**Issue by iCoobin** [QuintGao/GKPageScrollView#77]
![image](https://user-images.githubusercontent.com/9716454/132315757-6a355295-d392-4888-9b89-50b800126472.png)

复现路径 : 影评 和 讨论 快速切换的同时，下拉面板。

**Comment by iCoobin** [comment]
截图是 Lookin

**Comment by QuintGao** [comment]
最新版已修复

**Comment by iCoobin** [comment]
👍

**Comment by iCoobin** [comment]
上面的内容如果是 UITableView 的话也可以吗？ 是要把 tableView 拉长成contenSize大小再放到一个 View 上吗

**Comment by iCoobin** [comment]
我用 lookin 看豆瓣的视图层级，发现他那上面的 tableview 和下面的 tableview 的 pan 手势都禁用了，然后在最外层的viewController 上加了一个 pan 手势，应该是用最外层的 pan 手势做事件的传递。但是我不清楚他是怎么做到手势传递的。
