### ISSUE TITLE
childVCs的VC 的tableView 代理方法不走

### ISSUE THREAD

**Issue by duhongliang** [QuintGao/GKPageScrollView#8]
![WechatIMG272](https://user-images.githubusercontent.com/4090255/54734498-de893b00-4bda-11e9-982f-19d21c03da22.jpeg)

segmentView 下边三个vc，每个vc 有个tableview，
数据请求下来后， 调用了 currentVC.tableView reloadData, 但是 代理方法只执行了numberOfRowsInSection，返回的是3，
但是不执行cellforrowatindex

**Comment by QuintGao** [comment]
有具体实现的demo吗

**Comment by duhongliang** [comment]
> 有具体实现的demo吗

用的您这个demo，去掉了继承的basetableviewcontroller
![2731553147497_ pic](https://user-images.githubusercontent.com/4090255/54735359-b3a1e580-4be0-11e9-9834-3955b9def897.jpg)
![2741553147513_ pic_hd](https://user-images.githubusercontent.com/4090255/54735361-b43a7c00-4be0-11e9-90dd-2bd921d653e5.jpg)

**Comment by QuintGao** [comment]
![image](https://user-images.githubusercontent.com/13514024/54736137-b1da2100-4be4-11e9-834b-975c6ecbba9d.png)

你这里没有用懒加载，会创建多个控制器

**Comment by duhongliang** [comment]
> ![image](https://user-images.githubusercontent.com/13514024/54736137-b1da2100-4be4-11e9-834b-975c6ecbba9d.png)
> 
> 你这里没有用懒加载，会创建多个控制器

加载多个的话，应该tableview 应该也可以调用吧，
