### ISSUE TITLE
“滑动延续“时，title在顶部时，点击切换选项卡时，有时存在异常情况

### ISSUE THREAD

**Issue by luyouxing** [QuintGao/GKPageScrollView#87]

**Comment by luyouxing** [comment]
if (@available(iOS 15.0, *)) {
self.mainTableView.sectionHeaderTopPadding = 0;
}
低版本的情况  ，这句会报error!
可以改成这样不：        
if (@available(iOS 15.0, *)) {
[self.mainTableView setValue:@(0) forKey:@"sectionHeaderTopPadding"];
}

**Comment by QuintGao** [comment]
你是用的低版本的xcode吗

**Comment by luyouxing** [comment]
是的

**Comment by QuintGao** [comment]
> if (@available(iOS 15.0, *)) {
> self.mainTableView.sectionHeaderTopPadding = 0;
> }
> 低版本的情况 ，这句会报error!
> 可以改成这样不：
> if (@available(iOS 15.0, *)) {
> [self.mainTableView setValue:@(0) forKey:@"sectionHeaderTopPadding"];
> }

已修复
