### ISSUE TITLE
使用 uicollectionview 使用问题

### ISSUE THREAD

**Issue by 986138497** [QuintGao/GKPageScrollView#9]
你好,我发现使用uicollectionview ,如果数据源多的话没问题,数据源少的话会滑不动,  可以使用一个列表中只有一个数据源和20个数据源进行对比,滑到 menu 悬停的时候测试

**Comment by QuintGao** [comment]
你好，把UICollectionView的alwaysBounceVertical这个属性设置为YES就可以了。

**Comment by 986138497** [comment]
好的,解决了,谢谢,有没有上滑到某个位置,停住了,然后下拉加载的,不少微博发现页那种

**Comment by QuintGao** [comment]
我demo中有微博发现页的例子啊

**Comment by 986138497** [comment]
https://github.com/pujiaxin33/JXPageListView/blob/master/JXPageListView/Gif/headerLoading.gif  类似这种,大佬

**Comment by 986138497** [comment]
就是滑动上去后,能上拉刷新

**Comment by QuintGao** [comment]
这种就是刷新时机的问题，你可以在滑动到临界点后开始下拉刷新请求数据。
