### ISSUE TITLE
豆瓣效果，使用tableView样式，tableview使用plain style，添加section header，header 位置不正确

### ISSUE THREAD

**Issue by tteabag** [QuintGao/GKPageScrollView#91]
`
UITableView(frame: .zero, style: .plain)
`
`
func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        return toolV
    }
    
    func tableView(_ tableView: UITableView,
                   heightForHeaderInSection section: Int) -> CGFloat {
        return 51
    }
`
![Snip20211111_1](https://user-images.githubusercontent.com/16873237/141254093-6b5f937f-8a7c-43fd-87bd-cb37ff5162df.png)

**Comment by QuintGao** [comment]
因为内部修改了UITableView的contentInset，对sectionHeader悬浮有影响，所以会显示不准确

**Comment by tteabag** [comment]
> 因为内部修改了UITableView的contentInset，对sectionHeader悬浮有影响，所以会显示不准确

实现机制，没法修复吗，确认一下，好找其他方案

**Comment by QuintGao** [comment]
目前没找到解决方法
