### ISSUE TITLE
headerView的高度是写死了为 #define kDYHeaderHeight (kScreenW * 375.0f / 345.0f)

### ISSUE THREAD

**Issue by liyqxtu** [QuintGao/GKPageScrollView#93]
headerView的高度是写死了，#define kDYHeaderHeight (kScreenW * 375.0f / 345.0f)
无法根据子view的内容来自适应高度，建议使用UIStackView来实现

**Comment by QuintGao** [comment]
这个只是demo，实际情况可根据demo自行调整

**Comment by liyqxtu** [comment]
应该如何调整呢？有没有好的实现方法？
