### ISSUE TITLE
headerview的高度大于手机屏幕高度的时候 滑动到listview会产生卡顿的问题

### ISSUE THREAD

**Issue by noname004** [QuintGao/GKPageScrollView#94]
分析到了原因是 listview是加在GKPageTableView的cell上，当GKPageScrollView 的headerview高度大于整个屏幕的时候，GKPageTableView的cell不会在GKPageScrollView 的reloadData后立即加载布局ui，而是当这个cell即将出现的时候才去加载，这时候滑动到listview因为要加载cell上的listview就产生了卡顿，我尝试了把GKPageTableView  cell的高度设置为0，并把加载在GKPageTableView  cell上的内容加载在GKPageTableView的tablevFooterView上，成功解决了滑动卡顿的问题，但我担心会不会引起其它的一些问题，这里仅是抛砖引玉，希望作者能考虑这个问题。并在后续版本做出优化。

**Comment by QuintGao** [comment]
最新版为了兼容老版本增加了showInFooter属性，可以解决该问题。
