### ISSUE TITLE
GKPhotoBrowser+ GKPageScrollView 导致状态栏问题

### ISSUE THREAD

**Issue by ljbshishabi** [QuintGao/GKPageScrollView#96]
之前项目中使用GKPhotoBrowser浏览图片时是正常的
根据需求新增使用了GKPageScrollView

在图片预览界面拖拽或点击触发图片缩放动画途中可以看到状态栏消失了
在图片缩放动画完成之后状态栏出现 整个页面下移 回归正常

已知在非刘海屏出现
在有导航栏页面出现
设备信息 iPhone 8  iOS 14.8

**Comment by QuintGao** [comment]
有demo吗

**Comment by ljbshishabi** [comment]
[demo.zip](https://github.com/QuintGao/GKPageScrollView/files/7659525/demo.zip)

**Comment by ljbshishabi** [comment]
好像也不是GKPageScrollView的问题 把pod注释了也一样- -

**Comment by QuintGao** [comment]
这个是GKPhotoBrowser的问题，更新到2.3.4版本就好了。[2.3.4](https://github.com/QuintGao/GKPhotoBrowser/releases/tag/2.3.4)
